#!/bin/bash
touch DELETE.txt

for ((i=1; i<=15; i++)); do
    rand_text=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    
    echo "$rand_text" >> DELETE.txt
    
    git add DELETE.txt
    
    git commit -m "Commit $i: Random changes"
done
